config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/new'

  resources :tickets do
    resources :comments
  end

  resources :projects
  resources :teams

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  has_many :tickets
  belongs_to :teams, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  validates :title, presence: true
  has_many :projects
  has_and_belongs_to_many :users
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :comments
  belongs_to :projects, optional: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets, :dependent => :destroy
  has_and_belongs_to_many :teams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def display_name
    self[:display_name].presence || email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  private
    def user_not_authorized
      flash[:alert] = "You are not authorized to access this page."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to ticket_path(@ticket)
  end

  def destroy
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.find(params[:id])

    authorize @comment

    @comment.destroy
    redirect_to ticket_path(@ticket)
  end

  private
    def comment_params
      params.require(:comment).permit(:description)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to user_session_path and return
    end

    if params[:assignee_id]
      @tickets = Ticket.where(due_date: nil, assignee_id: params[:assignee_id]) # get tickets with no due date
      @sorted_tickets = Ticket.where(assignee_id: params[:assignee_id]).where.not(due_date: nil).group_by { |ticket| ticket.due_date.strftime("%B %Y") } # get tickets with due dates sorted by month
    else
      @tickets = Ticket.where(due_date: nil) # get tickets with no due date
      @sorted_tickets = Ticket.where.not(due_date: nil).group_by { |ticket| ticket.due_date.strftime("%B %d %Y") } # get tickets with due dates sorted by month
    end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects_grouped_by_team = Team.includes(:users).where('users.id = ?', current_user.id).references(:users)
  end

  def show
    @project = Project.find(params[:id])
    @team = Team.find(@project.team_id)

    authorize @project

    @tickets = Ticket.all.where(project_id: @project.id)
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    authorize @project

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    authorize @project

    if @project.update(project_params.merge(team_id: @project.team_id))
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    @project.destroy

    redirect_to projects_path
  end

  private

    def project_params
      params.require(:project).permit(:title, :description, :team_id)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:email, :display_name, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:email, :display_name, :password, :password_confirmation, :current_password)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_action :authenticate_user!

  def index
    @teams = Team.includes(:users).where('users.id = ?', current_user.id).references(:users)
  end

  def show
    @team = Team.find(params[:id])
    authorize @team
    @projects = Project.all.where(team_id: params[:id])
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
    authorize @team
  end

  def create
    @team = Team.new(team_params.merge(user_ids: [current_user.id]))

    if @team.save
      redirect_to @team
    else
      render 'new'
    end
  end

  def update
    @team = Team.find(params[:id])

    authorize @team

    if @team.update(team_params)
      redirect_to @team
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    authorize @team

    @team.destroy

    redirect_to teams_path
  end

  private

    def team_params
      params.require(:team).permit(:title, :description, :user_ids => [])
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :authenticate_user!

  def index
    redirect_to root_path
  end

  def show
    @ticket = Ticket.find(params[:id])

    if @ticket.assignee_id?
      @assignee = User.find(@ticket.assignee_id)
    end
  end

  def new
    @ticket = Ticket.new
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = Ticket.new(ticket_params.merge(user_id: current_user.id))

    if @ticket.save
      redirect_to @ticket
    else
      render 'new'
    end

  end

  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update(ticket_params.merge(project_id: @ticket.project_id))
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    redirect_to root_path
  end

  private
    def ticket_params
      params.require(:ticket).permit(:title, :description, :assignee_id, :due_date, :status, :project_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  def devise_get_name(id)
    id = id.to_i
    user = User.find(id)
    if user.display_name?
      user.display_name
    else
      user.email
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/comments/_comment.html.erb
<section class="heading small-margin">
  <strong><%= comment.user.display_name %> says:</strong>
  <nav><% if policy(comment).update? %>
    <%= link_to 'Delete', [comment.ticket, comment],
           method: :delete,
           data: { confirm: 'Are you sure?' },
           class: 'highlight blue' %>
  <% end %></nav>
</section>
<section class="cell margin-bottom">
  <p><%= comment.description %></p>
</section>

app/views/comments/edit.html.erb
<%= @comment.inspect %>
<h1>Edit Comment</h1>

<%= form_with(model: @comment, local: true) do |form| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back to Ticket', ticket_path(comment.ticket) %>

app/views/dashboard/index.html.erb
<section class="dashboard generic inner">

  <% if @tickets.count > 0 %>
    <section class="title-card margin-bottom">
      <section class="title">No Rush</section>
      <section class="card">
        <% @tickets.each do |ticket| %>
          <%= render :partial => '/tickets/row', :locals => { :ticket => ticket } %>
        <% end %>
      </section>
    </section><!-- / title-card -->
  <% end %>

  <% if @sorted_tickets.count > 0 %>
    <% @sorted_tickets.each do |due_date, tickets| %>
      <section class="title-card margin-bottom">
        <section class="title"><%= due_date %></section>
        <section class="card">
          <% tickets.each do |ticket| %>
            <%= render :partial => '/tickets/row', :locals => { :ticket => ticket } %>
          <% end %>
        </section>
      </section><!-- / title-card -->
    <% end %>
  <% end %>

  <% if @tickets.count == 0 && @sorted_tickets.count == 0 %>
    <div class="cell"><%= link_to 'Want to create a team?', new_team_path %></div>
  <% end %>
</section><!-- / inner -->

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <%= form.hidden_field :team_id, :value => params[:team_id] %>

  <%= form.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="form form-styles">
  <h1>Edit Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div class="inner">
  <section class="generic">

    <section class="heading">
      <h2>Your Projects</h2>
    </section>

    <% @projects_grouped_by_team.each do |team| %>
      <section class="heading">
        <h2><%= link_to team.title, team_url(team) %></h2>
        <nav><%= link_to 'Create Project', new_project_url(:team_id => team.id), class: 'highlight blue' %></nav>
      </section>

      <% if team.projects.any? %>
        <div class="projects margin-bottom">
          <% team.projects.each do |project| %>
            <div class="cell">
              <%= link_to project.title, project_path(project) %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>

  </section>
</div>

app/views/projects/new.html.erb
<div class="form form-styles">
  <h1>New Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="inner">
  <section class="generic">

    <section class="heading">
      <h2><%= @project.title  %></h2>
      <nav><%= link_to 'Edit', edit_project_path(@project), class: 'highlight blue' %> <%= link_to 'Delete', project_path(@project),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'highlight blue' %></nav>
    </section>

    <% if @project.description? %>
      <section class="cell margin-bottom"><p><%= @project.description %></p></section>
    <% end %>

    <h2 class="margin-bottom">Project Details</h2>

    <div class="cell margin-bottom"><p><strong>Team:</strong> <%= link_to @team.title, team_path(@team) %></div>

    <% if @team.users %>
      <div class="cell margin-bottom">
        <strong>Members: </strong><%= @team.users.map(&:display_name).join(', ') %>
      </div>
    <% end %>

    <section class="heading">
      <h2>Tickets</h2>
      <nav><%= link_to 'Create Ticket', new_ticket_url(:project_id => @project.id), class: 'highlight blue' %></nav>
    </section>

    <% if @tickets.any? %>
      <div class="tickets-list">
        <% @tickets.each do |ticket| %>
          <%= render :partial => '/tickets/row', :locals => { :ticket => ticket } %>
        <% end %>
      </div>
    <% else %>
      <div class="cell">Looks like you don't have any tickets. <%= link_to 'Would you like to create one?', new_ticket_url(:project_id => @project.id) %></div>
    <% end %>

  </section>

</div>

app/views/tickets/_form.html.erb
<%= form_with(model: @ticket, local: true) do |form| %>

  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ticket.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :assignee %><br>
    <%= form.collection_select(:assignee_id, User.all, :id, :email, include_blank: 'None', selected: @ticket.assignee_id) %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %><br>
    <%= form.date_field :due_date, class: 'form-control due-date-picker', disabled: true, id: 'due_date_picker' %>
  </div>

  <div class="form-group">
    <%= form.label :status %><br>
    <%= form.select(:status, options_for_select([
      ['To Do'],
      ['In Progress'],
      ['Done']
    ], @ticket.status)) %>
  </div>

  <%= form.hidden_field :project_id, :value => params[:project_id] %>

  <%= form.submit %>

<% end %>

app/views/tickets/_row.html.erb
<article class="ticket-row">

  <section class="ticket-title"><%= link_to ticket.title, ticket_path(ticket) %></section>
  <section class="ticket-details">

    <% if ticket.assignee_id? %>
      <section class="assignee highlight"><%= devise_get_name(ticket.assignee_id) %></section>
    <% end %>

    <%= link_to Project.find(ticket.project_id).title, project_url(ticket.project_id), class: 'highlight blue' %>
    <%= link_to Team.find(Project.find(ticket.project_id).team_id).title, team_url(Team.find(Project.find(ticket.project_id).team_id).id), class: 'highlight blue' %>
  </section><!-- / ticket-details -->
</article>

app/views/tickets/edit.html.erb
<div class="form form-styles">
  <h1>Edit Ticket</h1>
  <%= render 'form' %>
  <%= link_to 'Return to Ticket', ticket_url(@ticket) %>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New Ticket</h1>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="inner">
  <section class="generic">

    <section class="heading">
      <h2><%= @ticket.title  %></h2>
      <nav><%= link_to 'Edit', edit_ticket_path(@ticket), class: 'highlight blue' %> <%= link_to 'Delete', ticket_path(@ticket),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'highlight blue' %></nav>
    </section>

    <% if @ticket.description? %>
      <section class="cell margin-bottom">
        <%= @ticket.description %>
      </section>
    <% end %>

    <h2 class="margin-bottom">Ticket Details</h2>

    <div class="cell ticket-details margin-bottom">

      <% if @assignee %>
        <p>
          <strong>Assignee:</strong>
          <%= @assignee.email %>
        </p>
      <% end %>

      <% if @ticket.due_date %>
        <p>
          <strong>Due date:</strong>
          <%= l @ticket.due_date, format: :month_date_year_concise %>

        </p>
      <% end %>

      <p>
        <strong>Status:</strong>
        <%= @ticket.status %>
      </p>

      <% if @ticket.project_id %>
        <p>
          <strong>Project:</strong>
          <%= link_to Project.find(@ticket.project_id).title, project_path(@ticket.project_id) %>
        </p>
      <% end %>

    </div>

    <% if @ticket.comments.any? %>
      <h2 class="margin-bottom">Comments</h2>
      <div class="comments-list margin-bottom">
        <% @ticket.comments.each do |comment| %>
          <%= render comment %>
        <% end %>
      </div>
    <% end %>


    <h2 class="margin-bottom">Add a Comment</h2>
    <div class="cell form-styles">
      <%= form_with(model: [ @ticket, @ticket.comments.build ], local: true) do |form| %>
        <p>
          <%= form.label :description %><br>
          <%= form.text_area :description, class: 'form-control' %>
        </p>
        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>

  </section>

</div>